# EXAMPLE
[ai]
endpoint = "http://localhost:11434" # This is the default endpoint for ollama
model = "qwen2.5vl:3b" # This is the model I use
temperature = 0.2 # The lower the number the better

[vaults]
default = "recipies" # default vault
# Add your Obsidian vaults:
[[vaults.items]]
name = "recipies"
path = "/Users/me/Obsidian/recipies" # Use an absolute path