# EXAMPLE
[ai]
endpoint = "http://localhost:11434" # This is the default endpoint for ollama
model = "qwen2.5vl:3b" # This is the model I use
temperature = 0.2 # The lower the number the better for OCR

[vaults]
base_path = "/Users/me/Obsidian" # Folder where all your vaults live
default = "recipies" # default vault
# Add your Obsidian vaults (each is a folder named `name` inside base_path):
[[vaults.items]]
name = "recipies"
tags=[]
